const GRAVITY = 48.0;
const JUMP_FORCE = -720.0;
const MOVE_SPEED = 300.0;

const PLAYER_MAX_SIZE = 60;
const PLAYER_HITBOX_HEIGHT = 60;
const PLAYER_HITBOX_WIDTH = 30;
const PLAYER_MAX_HEALTH = 100;

const CANVAS_HEIGHT = 600;
const TILE_SIZE = 32;

const TARGET_FPS = 60;
const FRAME_TIME = 1.0 / TARGET_FPS;

const FIREBALL_POWER_MIN = 400.0;
const FIREBALL_POWER_MAX = 1000.0;
const FIREBALL_CHARGE_RATE = 500.0;
const FIREBALL_SIZE = 34;
const FIREBALL_RADIUS = FIREBALL_SIZE / 2;
const FIREBALL_MAX_DISTANCE = 1800.0;
const FIREBALL_DAMAGE = 30;
const FIREBALL_COOLDOWN = 0.8;
const FIREBALL_LIFETIME = 5.0;
const EXPLOSION_DURATION = 0.5;
const EXPLOSION_RADIUS = 40;
const SPECIAL_BEAM_RANGE = 2200.0;
const SPECIAL_BEAM_WIDTH = 54.0;
const SPECIAL_BEAM_DAMAGE = 12;
const SPECIAL_BEAM_TICK_INTERVAL = 0.12;

const ATTACK_DURATION = 0.2;

const GRID_CELL_SIZE = 128;

const DEAD_BODY_DURATION = 11.0;

const MAX_FAIRIES = 80;
const FAIRY_COLORS = [
  { r: 255, g: 200, b: 255 },
  { r: 200, g: 255, b: 200 },
  { r: 255, g: 255, b: 200 },
  { r: 200, g: 200, b: 255 },
  { r: 255, g: 200, b: 200 },
];

module.exports = {
  GRAVITY,
  JUMP_FORCE,
  MOVE_SPEED,
  PLAYER_MAX_SIZE,
  PLAYER_HITBOX_HEIGHT,
  PLAYER_HITBOX_WIDTH,
  PLAYER_MAX_HEALTH,
  CANVAS_HEIGHT,
  TILE_SIZE,
  TARGET_FPS,
  FRAME_TIME,
  FIREBALL_POWER_MIN,
  FIREBALL_POWER_MAX,
  FIREBALL_CHARGE_RATE,
  FIREBALL_SIZE,
  FIREBALL_RADIUS,
  FIREBALL_MAX_DISTANCE,
  FIREBALL_DAMAGE,
  FIREBALL_COOLDOWN,
  FIREBALL_LIFETIME,
  EXPLOSION_DURATION,
  EXPLOSION_RADIUS,
  SPECIAL_BEAM_RANGE,
  SPECIAL_BEAM_WIDTH,
  SPECIAL_BEAM_DAMAGE,
  SPECIAL_BEAM_TICK_INTERVAL,
  ATTACK_DURATION,
  GRID_CELL_SIZE,
  DEAD_BODY_DURATION,
  MAX_FAIRIES,
  FAIRY_COLORS,
};
