name: Sync to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Git LFS
        run: sudo apt-get update && sudo apt-get install -y git-lfs

      - name: Install Git Xet
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/huggingface/xet-core/refs/heads/main/git_xet/install.sh | sh
          git xet install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Grentjan35:$HF_TOKEN@huggingface.co/spaces/Grentjan35/SoulClash HEAD:main
